'use strict';

/**
 * Demo catalogue. Images live in /public/images/products/<slug>.webp.
 * Prices are in INR and GST-inclusive. Product names and trademarks belong to
 * their respective owners and are used here for demonstration only.
 */

const CATEGORIES = [
  {
    slug: 'mobiles',
    name: 'Mobiles',
    image: 'oneplus-nord-ce-2-5g',
    description: 'Smartphones for every budget.',
    tags: ['phone', 'smartphone', 'mobile'],
  },
  {
    slug: 'laptops',
    name: 'Laptops',
    image: 'apple-macbook-air-m1',
    description: 'Ultrabooks, everyday and creator laptops.',
    tags: ['laptop', 'notebook', 'computer'],
  },
  {
    slug: 'tablets',
    name: 'Tablets',
    image: 'apple-ipad-air-4th-gen',
    description: 'Tablets and 2-in-1s for work and play.',
    tags: ['tablet', 'ipad', 'tab'],
  },
  {
    slug: 'tvs-monitors',
    name: 'TVs & Monitors',
    image: 'lg-nanocell-55-4k-tv',
    description: 'Smart TVs and computer monitors.',
    tags: ['tv', 'television', 'monitor', 'screen', 'display'],
  },
  {
    slug: 'wearables-audio',
    name: 'Wearables & Audio',
    image: 'apple-watch-series-3',
    description: 'Smartwatches, fitness bands, earphones and smart speakers.',
    tags: ['wearable', 'audio', 'accessory', 'gadget'],
  },
  {
    slug: 'home-appliances',
    name: 'Home Appliances',
    image: 'philips-25l-digital-otg',
    description: 'Kitchen and laundry appliances.',
    tags: ['appliance', 'home', 'kitchen'],
  },
  {
    slug: 'furniture',
    name: 'Furniture',
    image: 'groovy-swivel-lounge-chair',
    description: 'Beds, seating, dining and storage.',
    tags: ['furniture', 'home', 'decor'],
  },
  {
    slug: 'mens-fashion',
    name: "Men's Fashion",
    image: 'mens-bomber-jacket-maroon',
    description: 'Shirts, jackets, suits, jeans and activewear.',
    tags: ['men', 'mens', 'clothing', 'fashion', 'apparel'],
  },
  {
    slug: 'womens-fashion',
    name: "Women's Fashion",
    image: 'womens-floral-fit-and-flare-dress',
    description: 'Dresses, tops and denim.',
    tags: ['women', 'womens', 'ladies', 'clothing', 'fashion', 'apparel'],
  },
  {
    slug: 'kids-fashion',
    name: "Kids' Fashion",
    image: 'girls-pineapple-print-dress',
    description: 'Everyday and festive wear for kids.',
    tags: ['kids', 'children', 'boys', 'girls', 'clothing', 'fashion'],
  },
];

const BRANDS = [
  'Apple',
  'Samsung',
  'OnePlus',
  'Xiaomi',
  'LG',
  'Dell',
  'HP',
  'Microsoft',
  'Amazon',
  'Philips',
  'Singer',
  'Usha',
  'Orpat',
  'Electrolux',
  'Whirlpool',
  'Nike',
  'Kartly Home',
  'Kartly Wear',
  'Kartly Kids',
];

// [slug, name, category, brand, price, mrp, stock, description, highlights, extra?]
const P = (
  slug,
  name,
  category,
  brand,
  price,
  mrp,
  stock,
  description,
  highlights = [],
  extra = {}
) => ({
  slug,
  name,
  category,
  brand,
  price,
  mrp,
  stock,
  description,
  highlights,
  ...extra,
});

const PRODUCTS = [
  /* ─────────── Mobiles ─────────── */
  P(
    'oneplus-nord-ce-2-5g',
    'OnePlus Nord CE 2 5G (Bahama Blue, 8GB RAM, 128GB)',
    'mobiles',
    'OnePlus',
    23999,
    25999,
    34,
    'A slim, fast 5G phone with a smooth AMOLED screen, a versatile 64MP camera and 65W SUPERVOOC charging that tops up a day of battery in about 15 minutes.',
    [
      '6.43" Fluid AMOLED display, 90Hz',
      'MediaTek Dimensity 900 5G',
      '64MP triple rear camera',
      '4500mAh battery with 65W SUPERVOOC',
    ],
    { featured: true, tags: ['5g', 'android'] }
  ),
  P(
    'redmi-note-11t-5g',
    'Redmi Note 11T 5G (6GB RAM, 128GB)',
    'mobiles',
    'Xiaomi',
    16999,
    19999,
    41,
    'Big-battery 5G value pick with a 90Hz display, a 50MP dual camera and 33W fast charging.',
    [
      '6.6" FHD+ 90Hz display',
      'MediaTek Dimensity 810',
      '50MP AI dual camera',
      '5000mAh battery, 33W fast charging',
    ],
    { tags: ['5g', 'android', 'redmi'] }
  ),
  P(
    'xiaomi-11i-5g',
    'Xiaomi 11i 5G (Purple Mist, 6GB RAM, 128GB)',
    'mobiles',
    'Xiaomi',
    24999,
    26999,
    22,
    'Flagship-style 120Hz AMOLED display with a 108MP main camera and 67W turbo charging.',
    [
      '6.67" 120Hz AMOLED display',
      'MediaTek Dimensity 920',
      '108MP triple camera',
      '5160mAh battery, 67W turbo charging',
    ],
    { tags: ['5g', 'android'] }
  ),
  P(
    'apple-iphone-11',
    'Apple iPhone 11 (Black, 64GB)',
    'mobiles',
    'Apple',
    43900,
    49900,
    28,
    'The dependable iPhone with a dual-camera system, Night mode and all-day battery life.',
    [
      '6.1" Liquid Retina HD display',
      'A13 Bionic chip',
      'Dual 12MP Ultra Wide and Wide cameras',
      'Night mode and 4K video',
    ],
    { featured: true, tags: ['iphone', 'ios'] }
  ),
  P(
    'apple-iphone-12-pro',
    'Apple iPhone 12 Pro (Gold, 128GB)',
    'mobiles',
    'Apple',
    99900,
    119900,
    9,
    'Pro camera system with LiDAR, a Super Retina XDR display and 5G in a surgical-grade stainless steel design.',
    [
      '6.1" Super Retina XDR display',
      'A14 Bionic chip',
      'Pro 12MP camera system with LiDAR',
      'Ceramic Shield front, 5G capable',
    ],
    { tags: ['iphone', 'ios', '5g'] }
  ),
  P(
    'apple-iphone-se',
    'Apple iPhone SE (White, 64GB)',
    'mobiles',
    'Apple',
    29999,
    39900,
    18,
    'Compact iPhone with the A13 Bionic chip, Touch ID and a great single camera with Portrait mode.',
    [
      '4.7" Retina HD display',
      'A13 Bionic chip',
      '12MP camera with Portrait mode',
      'Touch ID and wireless charging',
    ],
    { tags: ['iphone', 'ios', 'compact'] }
  ),
  P(
    'samsung-galaxy-s21-ultra-5g',
    'Samsung Galaxy S21 Ultra 5G (Phantom Black, 12GB RAM, 256GB)',
    'mobiles',
    'Samsung',
    105999,
    116999,
    7,
    'Samsung’s camera flagship: 108MP quad camera, 100x Space Zoom, S Pen support and a stunning 120Hz QHD+ display.',
    [
      '6.8" QHD+ Dynamic AMOLED 2X, 120Hz',
      '108MP quad camera with 100x Space Zoom',
      'S Pen support',
      '5000mAh battery',
    ],
    { tags: ['galaxy', 'android', '5g'] }
  ),
  P(
    'samsung-galaxy-m33-5g',
    'Samsung Galaxy M33 5G (6GB RAM, 128GB)',
    'mobiles',
    'Samsung',
    17999,
    24999,
    36,
    'A 6000mAh battery powerhouse with a 120Hz display, a 5nm processor and a 50MP quad camera.',
    ['6.6" FHD+ 120Hz display', 'Exynos 1280 (5nm)', '50MP quad camera', '6000mAh battery'],
    { tags: ['galaxy', 'android', '5g'] }
  ),
  P(
    'samsung-galaxy-f13',
    'Samsung Galaxy F13 (Nightsky Green, 4GB RAM, 64GB)',
    'mobiles',
    'Samsung',
    11999,
    14999,
    45,
    'Everyday phone with a Full HD+ screen, a 50MP triple camera and a 6000mAh battery that lasts for days.',
    ['6.6" FHD+ display', '50MP triple camera', '6000mAh battery', 'RAM Plus up to 8GB'],
    { tags: ['galaxy', 'android', 'budget'] }
  ),
  P(
    'samsung-galaxy-f12',
    'Samsung Galaxy F12 (Sea Green, 4GB RAM, 64GB)',
    'mobiles',
    'Samsung',
    10999,
    12999,
    3,
    'A budget-friendly Galaxy with a smooth 90Hz display, a 48MP quad camera and a 6000mAh battery.',
    ['6.5" HD+ 90Hz display', '48MP quad camera', '6000mAh battery', 'Exynos 850 processor'],
    { tags: ['galaxy', 'android', 'budget'] }
  ),
  P(
    'lg-wing-5g',
    'LG Wing 5G (Aurora Grey, 8GB RAM, 128GB)',
    'mobiles',
    'LG',
    54999,
    69990,
    0,
    'A one-of-a-kind swivel phone: rotate the main screen to reveal a second display for multitasking and gimbal-style video.',
    [
      'Swivel dual-screen design',
      '6.8" P-OLED main display + 3.9" second screen',
      'Snapdragon 765G 5G',
      '64MP triple camera with gimbal mode',
    ],
    { tags: ['5g', 'android', 'dual screen'] }
  ),

  /* ─────────── Laptops ─────────── */
  P(
    'apple-macbook-pro-14-m1-pro',
    'Apple MacBook Pro 14" (M1 Pro, 16GB, 512GB SSD)',
    'laptops',
    'Apple',
    194900,
    199900,
    6,
    'A pro laptop with the M1 Pro chip, a mini-LED Liquid Retina XDR display and the ports professionals need.',
    [
      '14.2" Liquid Retina XDR display',
      'Apple M1 Pro with 8-core CPU',
      '16GB unified memory, 512GB SSD',
      'Up to 17 hours of battery life',
    ],
    { tags: ['macbook', 'mac', 'macos'] }
  ),
  P(
    'apple-macbook-air-m1',
    'Apple MacBook Air 13.3" (M1, 8GB, 256GB SSD)',
    'laptops',
    'Apple',
    84900,
    99900,
    24,
    'Silent, fanless and fast — the M1 MacBook Air is the everyday laptop that lasts all day.',
    [
      '13.3" Retina display with True Tone',
      'Apple M1 chip with 8-core CPU',
      'Fanless, silent design',
      'Up to 18 hours of battery life',
    ],
    { featured: true, tags: ['macbook', 'mac', 'macos'] }
  ),
  P(
    'microsoft-surface-laptop-4',
    'Microsoft Surface Laptop 4 13.5" (Ryzen 5, 8GB, 256GB)',
    'laptops',
    'Microsoft',
    102999,
    109999,
    8,
    'Sleek and light with a vibrant PixelSense touchscreen and long battery life.',
    [
      '13.5" PixelSense touchscreen',
      'AMD Ryzen 5 4680U',
      '8GB RAM, 256GB SSD',
      'Up to 19 hours of battery life',
    ],
    { tags: ['surface', 'windows'] }
  ),
  P(
    'samsung-galaxy-book2',
    'Samsung Galaxy Book2 15.6" (Core i5 12th Gen, 8GB, 512GB)',
    'laptops',
    'Samsung',
    64990,
    79990,
    15,
    'A large-screen everyday laptop that connects seamlessly with your Galaxy phone.',
    [
      '15.6" Full HD display',
      '12th Gen Intel Core i5',
      '8GB RAM, 512GB SSD',
      'Windows 11 with backlit keyboard',
    ],
    { tags: ['galaxy book', 'windows'] }
  ),
  P(
    'samsung-galaxy-book2-pro',
    'Samsung Galaxy Book2 Pro 13.3" (Core i7 12th Gen, 16GB, 512GB)',
    'laptops',
    'Samsung',
    99990,
    124990,
    10,
    'An ultra-light Intel Evo laptop with a gorgeous AMOLED display.',
    [
      '13.3" FHD AMOLED display',
      '12th Gen Intel Core i7 (Intel Evo)',
      'Starts at just 870 g',
      '16GB RAM, 512GB SSD',
    ],
    { tags: ['galaxy book', 'windows', 'ultrabook'] }
  ),
  P(
    'lg-gram-14',
    'LG gram 14" (Core i5 11th Gen, 16GB, 512GB)',
    'laptops',
    'LG',
    74999,
    89999,
    12,
    'Under a kilogram yet built to military durability standards, with a tall 16:10 display.',
    [
      '14" WUXGA IPS display (16:10)',
      '11th Gen Intel Core i5 (Intel Evo)',
      'Ultra-light 999 g chassis',
      'MIL-STD-810G durability',
    ],
    { tags: ['gram', 'windows', 'ultrabook'] }
  ),
  P(
    'dell-inspiron-15-3511',
    'Dell Inspiron 15 3511 (Core i5 11th Gen, 8GB, 512GB SSD)',
    'laptops',
    'Dell',
    54990,
    62990,
    19,
    'A reliable 15.6" laptop for study and work, with Office Home & Student included.',
    [
      '15.6" FHD anti-glare display',
      'Intel Core i5-1135G7',
      '8GB RAM, 512GB SSD',
      'Windows 11 + MS Office Home & Student',
    ],
    { tags: ['inspiron', 'windows'] }
  ),
  P(
    'dell-vostro-3510',
    'Dell Vostro 3510 15.6" (Core i3 11th Gen, 8GB, 256GB SSD)',
    'laptops',
    'Dell',
    39990,
    46990,
    21,
    'A dependable business laptop with a spill-resistant keyboard and fast SSD storage.',
    ['15.6" FHD display', 'Intel Core i3-1115G4', '8GB RAM, 256GB SSD', 'Spill-resistant keyboard'],
    { tags: ['vostro', 'windows', 'business'] }
  ),
  P(
    'hp-15-ryzen-3-ember-red',
    'HP 15.6" Laptop (Ember Red, Ryzen 3, 8GB, 256GB SSD)',
    'laptops',
    'HP',
    36990,
    42990,
    16,
    'A colourful everyday laptop for browsing, classes and streaming.',
    [
      '15.6" HD display',
      'AMD Ryzen 3 processor',
      '8GB RAM, 256GB SSD',
      'Lightweight with long battery life',
    ],
    { tags: ['windows', 'budget'] }
  ),
  P(
    'hp-pavilion-17',
    'HP Pavilion 17.3" (Core i5, 8GB, 1TB HDD)',
    'laptops',
    'HP',
    52990,
    58990,
    4,
    'A big-screen laptop with a full-size keyboard and numeric keypad for spreadsheets and movies.',
    [
      '17.3" HD+ BrightView display',
      'Intel Core i5 processor',
      '8GB RAM, 1TB HDD',
      'Full-size keyboard with numeric keypad',
    ],
    { tags: ['pavilion', 'windows'] }
  ),

  /* ─────────── Tablets ─────────── */
  P(
    'apple-ipad-air-4th-gen',
    'Apple iPad Air 10.9" (4th Gen, Wi-Fi, 64GB, Green)',
    'tablets',
    'Apple',
    50900,
    54900,
    14,
    'All-screen design, the A14 Bionic chip and Apple Pencil (2nd gen) support in five fun colours.',
    [
      '10.9" Liquid Retina display',
      'A14 Bionic chip',
      'Touch ID in the top button',
      'Works with Apple Pencil (2nd gen)',
    ],
    { tags: ['ipad', 'ipados'] }
  ),
  P(
    'apple-ipad-pro-12-9-m1',
    'Apple iPad Pro 12.9" (M1, Wi-Fi, 128GB, Space Grey)',
    'tablets',
    'Apple',
    112900,
    112900,
    3,
    'The ultimate iPad with the M1 chip and a brilliant mini-LED Liquid Retina XDR display.',
    [
      '12.9" Liquid Retina XDR display',
      'Apple M1 chip',
      'Thunderbolt / USB 4 port',
      '12MP Ultra Wide front camera with Center Stage',
    ],
    { tags: ['ipad', 'ipados', 'pro'] }
  ),
  P(
    'microsoft-surface-pro-7',
    'Microsoft Surface Pro 7 12.3" (Core i5, 8GB, 128GB)',
    'tablets',
    'Microsoft',
    71999,
    82999,
    7,
    'Laptop-to-tablet versatility with a built-in kickstand and a detachable keyboard.',
    [
      '12.3" PixelSense touchscreen',
      '10th Gen Intel Core i5',
      'Built-in kickstand, USB-C and USB-A',
      'Up to 10.5 hours of battery life',
    ],
    { tags: ['surface', 'windows', '2-in-1'] }
  ),
  P(
    'microsoft-surface-go-3',
    'Microsoft Surface Go 3 10.5" (Pentium Gold, 8GB, 128GB)',
    'tablets',
    'Microsoft',
    57999,
    62999,
    9,
    'The most portable Surface — a full Windows 11 PC in a 10.5" tablet.',
    [
      '10.5" PixelSense touchscreen',
      'Intel Pentium Gold 6500Y',
      'Windows 11 Home in S mode',
      'Up to 11 hours of battery life',
    ],
    { tags: ['surface', 'windows', '2-in-1'] }
  ),
  P(
    'samsung-galaxy-tab-s7',
    'Samsung Galaxy Tab S7 11" (Wi-Fi, 128GB, Mystic Black)',
    'tablets',
    'Samsung',
    55999,
    65999,
    11,
    'A premium Android tablet with a 120Hz display, quad AKG speakers and an S Pen in the box.',
    ['11" 120Hz LTPS display', 'Snapdragon 865+', 'S Pen included', 'Quad speakers tuned by AKG'],
    { featured: true, tags: ['galaxy tab', 'android'] }
  ),
  P(
    'samsung-galaxy-tab-a8',
    'Samsung Galaxy Tab A8 10.5" (Wi-Fi, 32GB, Grey)',
    'tablets',
    'Samsung',
    17999,
    21999,
    26,
    'A family-friendly tablet for streaming, reading and video calls.',
    [
      '10.5" WUXGA display',
      'Quad speakers with Dolby Atmos',
      '7040mAh battery',
      'Expandable storage up to 1TB',
    ],
    { tags: ['galaxy tab', 'android'] }
  ),
  P(
    'samsung-galaxy-tab-s6-lite',
    'Samsung Galaxy Tab S6 Lite 10.4" with S Pen (Wi-Fi, 64GB)',
    'tablets',
    'Samsung',
    27999,
    31999,
    20,
    'Take notes and sketch naturally with the included S Pen on a sharp 10.4" screen.',
    [
      '10.4" WUXGA+ display',
      'S Pen included in the box',
      'Dolby Atmos dual speakers',
      '7040mAh battery',
    ],
    { tags: ['galaxy tab', 'android', 'stylus'] }
  ),

  /* ─────────── TVs & Monitors ─────────── */
  P(
    'lg-nanocell-55-4k-tv',
    'LG NanoCell 139 cm (55") 4K Ultra HD Smart TV',
    'tvs-monitors',
    'LG',
    64990,
    89990,
    8,
    'Pure, accurate colour with NanoCell technology and an AI 4K processor, plus webOS and the Magic Remote.',
    [
      '55" 4K NanoCell display',
      'α5 AI Processor 4K',
      'webOS with ThinQ AI and Magic Remote',
      'HDR10 Pro and Filmmaker Mode',
    ],
    { featured: true, tags: ['4k', 'smart tv', 'television'] }
  ),
  P(
    'xiaomi-smart-tv-5a-43',
    'Xiaomi Smart TV 5A 108 cm (43") Full HD Android TV',
    'tvs-monitors',
    'Xiaomi',
    25999,
    32999,
    17,
    'A great-value Android TV with Dolby Audio, Chromecast built in and PatchWall recommendations.',
    [
      '43" Full HD display with Vivid Picture Engine',
      'Android TV 11 with PatchWall',
      '24W Dolby Audio speakers',
      'Chromecast built in',
    ],
    { tags: ['smart tv', 'android tv', 'television', 'mi'] }
  ),
  P(
    'oneplus-tv-y1s-43',
    'OnePlus TV Y1S 108 cm (43") Full HD Smart Android TV',
    'tvs-monitors',
    'OnePlus',
    26999,
    29999,
    13,
    'A bezel-less Full HD Android TV with Gamma Engine picture processing and Dolby Audio.',
    [
      '43" Full HD bezel-less display',
      'Gamma Engine for sharper visuals',
      'Android TV 11 with Google Assistant',
      '20W Dolby Audio speakers',
    ],
    { tags: ['smart tv', 'android tv', 'television'] }
  ),
  P(
    'dell-27-curved-gaming-monitor',
    'Dell 27" Curved Gaming Monitor (S2721HGF, 144Hz)',
    'tvs-monitors',
    'Dell',
    22999,
    28999,
    14,
    'An immersive 1500R curve with a fast 144Hz refresh rate and FreeSync Premium for tear-free gaming.',
    [
      '27" Full HD 1500R curved VA panel',
      '144Hz refresh rate, 1ms MPRT',
      'AMD FreeSync Premium',
      'Height-adjustable stand',
    ],
    { tags: ['monitor', 'gaming', 'curved'] }
  ),
  P(
    'dell-22-full-hd-monitor',
    'Dell 21.5" Full HD Monitor (E2222H)',
    'tvs-monitors',
    'Dell',
    8999,
    10999,
    30,
    'An affordable, eye-friendly monitor for home and office desks.',
    [
      '21.5" Full HD VA panel',
      'Anti-glare 3H hard coating',
      'VGA and DisplayPort inputs',
      'ComfortView low blue light',
    ],
    { tags: ['monitor', 'office'] }
  ),

  /* ─────────── Wearables & Audio ─────────── */
  P(
    'apple-watch-series-3',
    'Apple Watch Series 3 GPS 38mm (Space Grey Aluminium)',
    'wearables-audio',
    'Apple',
    19900,
    20900,
    16,
    'Track workouts, close your rings and stay connected — the easiest way into Apple Watch.',
    [
      'Optical heart sensor',
      'Water resistant to 50 metres',
      'Activity rings and workout tracking',
      'watchOS with Siri',
    ],
    { tags: ['smartwatch', 'watch', 'fitness'] }
  ),
  P(
    'oneplus-band',
    'OnePlus Band Smart Fitness Tracker',
    'wearables-audio',
    'OnePlus',
    2499,
    3999,
    52,
    'A lightweight band with SpO2 and 24×7 heart-rate tracking and two weeks of battery.',
    [
      '1.1" AMOLED touch display',
      'SpO2 and 24×7 heart-rate monitoring',
      '13 exercise modes',
      'Up to 14 days of battery life',
    ],
    { tags: ['fitness band', 'tracker', 'fitness'] }
  ),
  P(
    'mi-smart-band-5',
    'Mi Smart Band 5',
    'wearables-audio',
    'Xiaomi',
    2499,
    2999,
    48,
    'Colourful AMOLED band with 11 sports modes and 5ATM water resistance.',
    [
      '1.1" AMOLED colour display',
      '11 sports modes, 5ATM water resistant',
      'Heart-rate and sleep monitoring',
      'Up to 14 days of battery life',
    ],
    { tags: ['fitness band', 'tracker', 'fitness', 'mi'] }
  ),
  P(
    'mi-smart-band-6',
    'Mi Smart Band 6 (AMOLED)',
    'wearables-audio',
    'Xiaomi',
    3499,
    3999,
    39,
    'A bigger full-screen AMOLED display, SpO2 tracking and 30 fitness modes.',
    [
      '1.56" full-screen AMOLED display',
      'SpO2 tracking',
      '30 fitness modes',
      'Up to 14 days of battery life',
    ],
    { tags: ['fitness band', 'tracker', 'fitness', 'mi'] }
  ),
  P(
    'oneplus-bullets-wireless-z',
    'OnePlus Bullets Wireless Z Bass Edition (Blue)',
    'wearables-audio',
    'OnePlus',
    1999,
    2299,
    60,
    'Punchy bass, magnetic quick-switch and Warp Charge: 10 minutes for 10 hours of music.',
    [
      'Bass-boosted 12.4mm drivers',
      'Warp Charge: 10 min for 10 hours',
      'Up to 17 hours of playback',
      'IP55 sweat and water resistance',
    ],
    { tags: ['earphones', 'neckband', 'bluetooth', 'headphones'] }
  ),
  P(
    'amazon-echo-dot-3rd-gen',
    'Amazon Echo Dot (3rd Gen) Smart Speaker with Alexa',
    'wearables-audio',
    'Amazon',
    3499,
    4499,
    33,
    'Ask Alexa to play music, set reminders, answer questions and control your smart home.',
    [
      'Alexa voice assistant',
      'Improved speaker with richer sound',
      'Controls compatible smart home devices',
      'Hands-free calling and reminders',
    ],
    { tags: ['smart speaker', 'alexa', 'speaker'] }
  ),
  P(
    'microsoft-arc-mouse',
    'Microsoft Arc Bluetooth Mouse (Poppy Red)',
    'wearables-audio',
    'Microsoft',
    5999,
    6999,
    5,
    'An iconic travel mouse that snaps flat to slip into your bag and curves to fit your hand.',
    [
      'Snaps flat for travel',
      'Bluetooth LE connectivity',
      'Full scroll plane touch surface',
      'Up to 6 months of battery life',
    ],
    { tags: ['mouse', 'accessory', 'bluetooth'] }
  ),

  /* ─────────── Home Appliances ─────────── */
  P(
    'philips-25l-digital-otg',
    'Philips 25L Digital Oven Toaster Grill (HD6975)',
    'home-appliances',
    'Philips',
    8999,
    11995,
    18,
    'Bake, grill and toast with digital controls, preset menus and a motorised rotisserie.',
    [
      '25 L capacity with rotisserie',
      'Digital controls with preset menus',
      'Opti-Temp technology for even heating',
      'Includes baking tray and grill rack',
    ],
    { tags: ['oven', 'otg', 'kitchen', 'baking'] }
  ),
  P(
    'singer-fp57-food-processor',
    'Singer FP57 Food Processor',
    'home-appliances',
    'Singer',
    4299,
    5490,
    12,
    'One machine to chop, slice, grate, juice and blend — built for Indian kitchens.',
    [
      'Multi-purpose food processor',
      'Juicer, blender and chopping attachments',
      'Stainless-steel blades',
      'Overload protection',
    ],
    { tags: ['food processor', 'kitchen', 'mixer'] }
  ),
  P(
    'singer-mg46-mixer-grinder',
    'Singer MG-46 Mixer Grinder (3 Jars)',
    'home-appliances',
    'Singer',
    2599,
    3290,
    25,
    'A sturdy everyday mixer grinder for chutneys, batters and masalas.',
    [
      'Powerful motor for daily grinding',
      '3 stainless-steel jars',
      'Speed control with pulse function',
      'Overload protection',
    ],
    { tags: ['mixer', 'grinder', 'kitchen'] }
  ),
  P(
    'philips-perfectcare-steam-iron',
    'Philips PerfectCare Steam Iron',
    'home-appliances',
    'Philips',
    3299,
    4295,
    22,
    'One perfect temperature for all ironable fabrics — no burns, no settings to fiddle with.',
    [
      'OptimalTEMP technology',
      'Continuous steam for faster ironing',
      'SteamGlide soleplate',
      'Safe on all ironable fabrics',
    ],
    { tags: ['iron', 'steam iron', 'laundry'] }
  ),
  P(
    'usha-steam-iron',
    'Usha Steam Iron (Blue)',
    'home-appliances',
    'Usha',
    1299,
    1690,
    30,
    'Steam, spray and dry ironing in one lightweight iron with a non-stick soleplate.',
    [
      'Steam, dry and spray modes',
      'Non-stick coated soleplate',
      'Adjustable thermostat',
      'Self-clean function',
    ],
    { tags: ['iron', 'steam iron', 'laundry'] }
  ),
  P(
    'orpat-dry-iron',
    'Orpat Dry Iron (Sky Blue)',
    'home-appliances',
    'Orpat',
    699,
    899,
    40,
    'A simple, lightweight dry iron with a temperature dial — perfect for daily use.',
    ['Lightweight dry iron', 'Non-stick soleplate', 'Temperature control dial', 'Indicator light'],
    { tags: ['iron', 'dry iron', 'laundry'] }
  ),
  P(
    'electrolux-7kg-front-load',
    'Electrolux 7 kg Front Load Washing Machine',
    'home-appliances',
    'Electrolux',
    28990,
    34990,
    6,
    'Gentle yet thorough washing with steam care and a quiet inverter motor.',
    [
      '7 kg capacity, 1200 RPM',
      'Steam care for fewer wrinkles',
      'Quick 15-minute wash',
      'Inverter motor',
    ],
    { tags: ['washing machine', 'laundry', 'front load'] }
  ),
  P(
    'whirlpool-7kg-front-load',
    'Whirlpool Fresh Care 7 kg Front Load Washing Machine',
    'home-appliances',
    'Whirlpool',
    31990,
    38990,
    5,
    'FreshCare technology keeps washed clothes fresh in the drum for hours after the cycle ends.',
    [
      '7 kg capacity, 1200 RPM',
      'FreshCare+ keeps clothes fresh for hours',
      'Steam wash for allergen removal',
      'Inverter motor',
    ],
    { tags: ['washing machine', 'laundry', 'front load'] }
  ),

  /* ─────────── Furniture ─────────── */
  P(
    'groovy-swivel-lounge-chair',
    'Groovy Swivel Lounge Chair (Mustard)',
    'furniture',
    'Kartly Home',
    18499,
    22999,
    9,
    'A deep, cocooning swivel chair in soft mustard velvet — the reading corner upgrade you deserve.',
    [
      '360° swivel base',
      'Velvet upholstery',
      'High-density foam seat',
      'Assembled dimensions: 84 × 84 × 76 cm',
    ],
    { featured: true, tags: ['chair', 'lounge chair', 'living room'] }
  ),
  P(
    'sculpted-lounge-chairs-set-of-2',
    'Sculpted Lounge Chairs, Set of 2 (Crimson)',
    'furniture',
    'Kartly Home',
    32999,
    39999,
    4,
    'Statement lounge chairs with a sculpted, low-slung silhouette in bold crimson.',
    [
      'Set of 2 chairs',
      'Sculpted foam over steel frame',
      'Stain-resistant fabric',
      'No assembly required',
    ],
    { tags: ['chair', 'lounge chair', 'living room'] }
  ),
  P(
    'moon-swivel-accent-chair',
    'Moon Swivel Accent Chair (Ivory)',
    'furniture',
    'Kartly Home',
    14999,
    17999,
    11,
    'A plush, rounded accent chair on a swivel base, upholstered in cosy ivory boucle.',
    ['360° swivel base', 'Boucle upholstery', 'Plush rounded seat', 'Weight capacity 120 kg'],
    { tags: ['chair', 'accent chair', 'living room'] }
  ),
  P(
    'tufted-queen-bed-led-headboard',
    'Tufted Queen Bed with LED Headboard (White)',
    'furniture',
    'Kartly Home',
    42999,
    52999,
    5,
    'Button-tufted headboard with soft ambient LED lighting on a sturdy engineered-wood frame.',
    [
      'Queen size (fits 152 × 198 cm mattress)',
      'Button-tufted headboard with LED strip',
      'Engineered wood with slatted base',
      'Mattress not included',
    ],
    { tags: ['bed', 'queen bed', 'bedroom'] }
  ),
  P(
    'channel-tufted-upholstered-bed',
    'Channel-Tufted Upholstered King Bed (Grey)',
    'furniture',
    'Kartly Home',
    38999,
    46999,
    6,
    'A tall channel-tufted headboard in grey fabric on slim mid-century legs.',
    [
      'King size (fits 182 × 198 cm mattress)',
      'Channel-tufted fabric headboard',
      'Solid wood legs',
      'Mattress not included',
    ],
    { tags: ['bed', 'king bed', 'bedroom'] }
  ),
  P(
    'wingback-upholstered-bed',
    'Wingback Upholstered Queen Bed (Ivory)',
    'furniture',
    'Kartly Home',
    45999,
    54999,
    4,
    'A hotel-style wingback bed with a padded headboard that wraps around you.',
    [
      'Queen size (fits 152 × 198 cm mattress)',
      'Wingback padded headboard',
      'Low-profile upholstered frame',
      'Mattress not included',
    ],
    { tags: ['bed', 'queen bed', 'bedroom'] }
  ),
  P(
    'sheesham-wood-king-bed',
    'Sheesham Wood King Bed (Walnut Finish)',
    'furniture',
    'Kartly Home',
    36999,
    44999,
    7,
    'Solid sheesham wood in a warm walnut finish — built to last for generations.',
    [
      'King size (fits 182 × 198 cm mattress)',
      'Solid sheesham wood',
      'Walnut finish with carved headboard',
      'Mattress not included',
    ],
    { tags: ['bed', 'king bed', 'bedroom', 'wooden'] }
  ),
  P(
    'convertible-sofa-bed',
    'Convertible 3-Seater Sofa Bed (Charcoal)',
    'furniture',
    'Kartly Home',
    24999,
    31999,
    10,
    'A clean-lined sofa by day that folds flat into a guest bed by night.',
    [
      'Converts from sofa to bed in seconds',
      'Charcoal woven fabric',
      'Steel frame with chrome legs',
      'Seats three comfortably',
    ],
    { tags: ['sofa', 'sofa bed', 'living room'] }
  ),
  P(
    'royal-carved-chaise-lounge',
    'Royal Carved Chaise Lounge (Ivory & Gold)',
    'furniture',
    'Kartly Home',
    54999,
    64999,
    2,
    'A hand-carved chaise with gilded detailing and tufted ivory upholstery.',
    [
      'Hand-carved solid wood frame',
      'Gold-leaf finish',
      'Tufted ivory upholstery',
      'Includes bolster cushion',
    ],
    { tags: ['sofa', 'chaise', 'living room'] }
  ),
  P(
    'victorian-dining-set-with-hutch',
    'Victorian Carved Dining Set with Hutch',
    'furniture',
    'Kartly Home',
    89999,
    109999,
    2,
    'A round pedestal table, four upholstered chairs and a matching display hutch in rich carved wood.',
    [
      'Round pedestal table + 4 chairs',
      'Matching glass-front display hutch',
      'Hand-carved hardwood',
      'Upholstered seats',
    ],
    { tags: ['dining table', 'dining set', 'dining room'] }
  ),
  P(
    'solid-wood-4-seater-dining-set',
    'Solid Wood 4-Seater Dining Set',
    'furniture',
    'Kartly Home',
    24999,
    29999,
    8,
    'A compact dining set in dark sheesham wood with slatted high-back chairs.',
    ['Table + 4 chairs', 'Solid sheesham wood', 'Walnut finish', 'Table: 120 × 75 × 76 cm'],
    { tags: ['dining table', 'dining set', 'dining room', 'wooden'] }
  ),
  P(
    'study-table-with-drawers',
    'Study Table with Drawers (Wenge & White)',
    'furniture',
    'Kartly Home',
    9999,
    12999,
    18,
    'A tidy workstation with a three-drawer pedestal and a keyboard-friendly desktop.',
    ['3 storage drawers', 'Engineered wood', 'Wenge and white finish', 'Desk: 110 × 60 × 75 cm'],
    { tags: ['desk', 'study table', 'office', 'work from home'] }
  ),
  P(
    'l-shaped-office-desk-with-hutch',
    'L-Shaped Office Desk with Hutch (Oak)',
    'furniture',
    'Kartly Home',
    27999,
    33999,
    5,
    'A corner desk with a tall hutch for files and books — made for serious home offices.',
    [
      'L-shaped corner design',
      'Hutch with shelves and cabinets',
      'Keyboard tray and CPU space',
      'Oak finish',
    ],
    { tags: ['desk', 'office', 'work from home'] }
  ),
  P(
    'two-door-wardrobe-with-mirror',
    '2-Door Wardrobe with Mirror (White)',
    'furniture',
    'Kartly Home',
    19999,
    24999,
    7,
    'A bright white wardrobe with a full-length mirror, hanging space and drawers.',
    [
      '2 doors with full-length mirror',
      'Hanging rail and 4 shelves',
      'Engineered wood',
      '90 × 55 × 190 cm',
    ],
    { tags: ['wardrobe', 'storage', 'bedroom'] }
  ),
  P(
    'moon-gate-display-shelf',
    'Moon Gate Display Shelf (Solid Wood)',
    'furniture',
    'Kartly Home',
    21999,
    25999,
    3,
    'A sculptural circular shelf with staggered compartments above three drawers.',
    [
      'Circular moon-gate silhouette',
      'Solid wood construction',
      'Three storage drawers',
      'Ideal for books and decor',
    ],
    { tags: ['shelf', 'bookshelf', 'storage', 'decor'] }
  ),

  /* ─────────── Men’s Fashion ─────────── */
  P(
    'nike-dri-fit-training-tshirt',
    "Nike Dri-FIT Men's Training T-Shirt (Black)",
    'mens-fashion',
    'Nike',
    1695,
    1995,
    64,
    'Sweat-wicking Dri-FIT fabric keeps you dry and comfortable from warm-up to cool-down.',
    ['Dri-FIT moisture-wicking fabric', 'Standard fit', 'Crew neck', 'Machine wash'],
    { featured: true, tags: ['t-shirt', 'tshirt', 'tee', 'sportswear', 'gym'] }
  ),
  P(
    'nike-dri-fit-academy-shorts',
    "Nike Dri-FIT Academy Men's Shorts (Black)",
    'mens-fashion',
    'Nike',
    1295,
    1495,
    50,
    'Lightweight training shorts with an elastic waistband and Dri-FIT technology.',
    ['Dri-FIT fabric', 'Elastic waistband with drawcord', 'Side pockets', 'Machine wash'],
    { tags: ['shorts', 'sportswear', 'gym'] }
  ),
  P(
    'mens-slim-fit-joggers-grey',
    "Men's Slim-Fit Joggers (Grey Melange)",
    'mens-fashion',
    'Kartly Wear',
    999,
    1499,
    58,
    'Soft cotton-blend joggers with a tapered leg and ribbed cuffs.',
    ['Cotton-rich fleece', 'Slim, tapered fit', 'Elastic waist with drawstring', 'Zip pockets'],
    { tags: ['joggers', 'track pants', 'trousers', 'casual'] }
  ),
  P(
    'mens-zip-up-track-jacket',
    "Men's Zip-Up Track Jacket (Black)",
    'mens-fashion',
    'Kartly Wear',
    1799,
    2499,
    27,
    'A classic high-neck track jacket with contrast-striped cuffs and hem.',
    ['Full-length zip', 'Contrast striped trims', 'Regular fit', 'Machine wash'],
    { tags: ['jacket', 'track jacket', 'winterwear'] }
  ),
  P(
    'mens-sherpa-lined-hoodie-cardigan',
    "Men's Sherpa-Lined Hooded Cardigan (Charcoal)",
    'mens-fashion',
    'Kartly Wear',
    2299,
    2999,
    19,
    'A chunky knit cardigan with a warm sherpa-lined hood for chilly evenings.',
    ['Chunky knit outer', 'Sherpa-lined hood', 'Button front', 'Regular fit'],
    { tags: ['cardigan', 'sweater', 'hoodie', 'winterwear'] }
  ),
  P(
    'mens-bomber-jacket-maroon',
    "Men's Bomber Jacket (Maroon)",
    'mens-fashion',
    'Kartly Wear',
    2999,
    3999,
    23,
    'A smart-casual bomber with ribbed trims in a rich maroon.',
    [
      'Lightweight shell',
      'Ribbed collar, cuffs and hem',
      'Zip front with side pockets',
      'Regular fit',
    ],
    { tags: ['jacket', 'bomber', 'winterwear'] }
  ),
  P(
    'mens-slim-fit-formal-shirt-black',
    "Men's Slim-Fit Formal Shirt (Black)",
    'mens-fashion',
    'Kartly Wear',
    1199,
    1599,
    44,
    'A crisp cotton-blend shirt that goes from boardroom to dinner.',
    ['Cotton blend', 'Slim fit', 'Spread collar', 'Machine wash'],
    { tags: ['shirt', 'formal', 'office'] }
  ),
  P(
    'mens-two-piece-suit-black',
    "Men's Two-Piece Slim-Fit Suit (Black)",
    'mens-fashion',
    'Kartly Wear',
    7999,
    10999,
    12,
    'A sharp two-button suit with a notch lapel and flat-front trousers.',
    ['Jacket + trousers', 'Slim fit', 'Notch lapel, two-button', 'Dry clean only'],
    { tags: ['suit', 'blazer', 'formal', 'wedding'] }
  ),
  P(
    'mens-contrast-lapel-blazer-navy',
    "Men's Contrast-Lapel Blazer (Navy)",
    'mens-fashion',
    'Kartly Wear',
    3499,
    4999,
    16,
    'A navy blazer with black contrast lapels for a modern party look.',
    ['Contrast satin lapels', 'Slim fit', 'Single-button closure', 'Dry clean only'],
    { tags: ['blazer', 'party', 'formal'] }
  ),
  P(
    'mens-casual-shirt-khaki',
    "Men's Cotton Casual Shirt (Khaki)",
    'mens-fashion',
    'Kartly Wear',
    899,
    1299,
    38,
    'An easy-wearing cotton shirt in a versatile khaki.',
    ['100% cotton', 'Regular fit', 'Button-down collar', 'Machine wash'],
    { tags: ['shirt', 'casual'] }
  ),
  P(
    'mens-slim-fit-jeans-light-blue',
    "Men's Slim-Fit Jeans (Light Blue)",
    'mens-fashion',
    'Kartly Wear',
    1499,
    2199,
    47,
    'Stretch denim in a light wash with a comfortable slim fit.',
    ['Stretch denim', 'Slim fit, mid-rise', 'Five-pocket styling', 'Machine wash'],
    { tags: ['jeans', 'denim', 'trousers'] }
  ),
  P(
    'mens-stretch-chinos-beige',
    "Men's Stretch Chinos (Beige)",
    'mens-fashion',
    'Kartly Wear',
    1299,
    1799,
    35,
    'Smart-casual chinos with a hint of stretch for all-day comfort.',
    ['Cotton with elastane', 'Slim fit', 'Flat front', 'Machine wash'],
    { tags: ['chinos', 'trousers', 'casual'] }
  ),
  P(
    'mens-utility-cargo-joggers',
    "Men's Utility Cargo Joggers (Black)",
    'mens-fashion',
    'Kartly Wear',
    1399,
    1999,
    29,
    'Street-style cargo joggers with utility pockets and adjustable cuffs.',
    [
      'Multiple utility pockets',
      'Elastic waist with drawcord',
      'Tapered fit with cuffed hem',
      'Machine wash',
    ],
    { tags: ['joggers', 'cargo', 'trousers', 'streetwear'] }
  ),

  /* ─────────── Women’s Fashion ─────────── */
  P(
    'womens-floral-fit-and-flare-dress',
    "Women's Floral Fit & Flare Dress",
    'womens-fashion',
    'Kartly Wear',
    1899,
    2499,
    31,
    'A vintage-inspired floral dress with a fitted bodice and full swing skirt.',
    ['Fit and flare silhouette', 'Sleeveless with round neck', 'Knee length', 'Hand wash'],
    { featured: true, tags: ['dress', 'floral', 'party'] }
  ),
  P(
    'womens-colour-block-bodycon-dress',
    "Women's Colour-Block Bodycon Dress (Black & Red)",
    'womens-fashion',
    'Kartly Wear',
    1599,
    2199,
    24,
    'A figure-flattering bodycon dress with bold red colour-block panels.',
    ['Bodycon fit', 'Three-quarter sleeves', 'Knee length', 'Stretch fabric'],
    { tags: ['dress', 'bodycon', 'office', 'party'] }
  ),
  P(
    'womens-sheer-yoke-skater-dress',
    "Women's Sheer-Yoke Skater Dress (Black)",
    'womens-fashion',
    'Kartly Wear',
    1299,
    1799,
    27,
    'A little black dress with a sheer mesh yoke and a playful skater skirt.',
    ['Skater silhouette', 'Sheer mesh yoke', 'Long sleeves', 'Above knee length'],
    { tags: ['dress', 'black dress', 'party'] }
  ),
  P(
    'womens-lace-midi-dress',
    "Women's Lace Midi Dress (Black)",
    'womens-fashion',
    'Kartly Wear',
    2199,
    2999,
    15,
    'Elegant all-over lace in a flattering midi length for evenings out.',
    ['All-over lace', 'Short sleeves', 'Midi length', 'Lined skirt'],
    { tags: ['dress', 'lace', 'party', 'evening'] }
  ),
  P(
    'womens-ruffled-floral-mini-dress',
    "Women's Ruffled Floral Mini Dress",
    'womens-fashion',
    'Kartly Wear',
    1499,
    1999,
    20,
    'A breezy chiffon mini dress with ruffles and a tie waist.',
    ['Lightweight chiffon', 'Ruffle details', 'Tie waist', 'Mini length'],
    { tags: ['dress', 'floral', 'summer'] }
  ),
  P(
    'womens-printed-tunic-dress',
    "Women's Printed Tunic Dress (Fuchsia)",
    'womens-fashion',
    'Kartly Wear',
    999,
    1499,
    42,
    'A comfortable printed tunic with an embellished neckline.',
    ['Soft rayon fabric', 'Embellished neckline', 'Short sleeves', 'Machine wash'],
    { tags: ['dress', 'tunic', 'casual'] }
  ),
  P(
    'womens-pinafore-dress',
    "Women's Wool-Blend Pinafore Dress (Charcoal)",
    'womens-fashion',
    'Kartly Wear',
    1799,
    2499,
    13,
    'A smart pinafore dress with a belted waist — layer it over a turtleneck.',
    ['Wool-blend fabric', 'Belted waist', 'Above knee length', 'Dry clean recommended'],
    { tags: ['dress', 'pinafore', 'winterwear', 'office'] }
  ),
  P(
    'womens-high-rise-skinny-jeans',
    "Women's High-Rise Skinny Jeans (Black)",
    'womens-fashion',
    'Kartly Wear',
    1499,
    1999,
    37,
    'Sculpting high-rise skinny jeans in a deep black stretch denim.',
    ['Stretch denim', 'High rise', 'Skinny fit', 'Machine wash'],
    { tags: ['jeans', 'denim', 'trousers'] }
  ),

  /* ─────────── Kids’ Fashion ─────────── */
  P(
    'boys-tshirt-and-capri-set',
    "Boys' T-Shirt & Capri Set (Mustard)",
    'kids-fashion',
    'Kartly Kids',
    699,
    999,
    40,
    'A comfy cotton co-ord set for playdates and weekends.',
    ['100% cotton', 'Printed T-shirt + capri', 'Elastic waist', 'Ages 2–8 years'],
    { tags: ['boys', 'kids', 'set', 't-shirt', 'tshirt'] }
  ),
  P(
    'girls-pineapple-print-dress',
    "Girls' Pineapple Print Dress",
    'kids-fashion',
    'Kartly Kids',
    799,
    1099,
    33,
    'A cheerful summer dress with a pineapple print and flutter sleeves.',
    ['Soft cotton', 'Flutter sleeves', 'Back button closure', 'Ages 3–10 years'],
    { tags: ['girls', 'kids', 'dress', 'summer'] }
  ),
  P(
    'boys-silk-kurta-pyjama-set',
    "Boys' Silk Kurta Pyjama Set (Teal & Maroon)",
    'kids-fashion',
    'Kartly Kids',
    1199,
    1599,
    21,
    'A festive silk-blend kurta with a contrasting pyjama — perfect for celebrations.',
    ['Silk-blend kurta', 'Cotton pyjama', 'Mandarin collar', 'Ages 2–12 years'],
    { tags: ['boys', 'kids', 'ethnic', 'kurta', 'festive'] }
  ),
  P(
    'boys-checked-casual-shirt',
    "Boys' Checked Casual Shirt",
    'kids-fashion',
    'Kartly Kids',
    599,
    899,
    36,
    'A classic checked shirt layered over a graphic tee for an easy weekend look.',
    ['Cotton checked shirt', 'Roll-up sleeves', 'Button front', 'Ages 4–12 years'],
    { tags: ['boys', 'kids', 'shirt'] }
  ),
  P(
    'boys-embroidered-sherwani-set',
    "Boys' Embroidered Sherwani Set (Sky Blue)",
    'kids-fashion',
    'Kartly Kids',
    1899,
    2599,
    4,
    'A richly embroidered sherwani with churidar and dupatta for weddings and festivals.',
    ['Embroidered sherwani', 'Churidar and dupatta included', 'Mandarin collar', 'Ages 2–12 years'],
    { tags: ['boys', 'kids', 'ethnic', 'sherwani', 'wedding', 'festive'] }
  ),
  P(
    'girls-anarkali-kurta-set',
    "Girls' Anarkali Kurta Set (Yellow)",
    'kids-fashion',
    'Kartly Kids',
    1299,
    1799,
    17,
    'A flared anarkali with embroidered yoke, leggings and a contrast dupatta.',
    [
      'Flared anarkali kurta',
      'Leggings and dupatta included',
      'Embroidered yoke',
      'Ages 3–12 years',
    ],
    { tags: ['girls', 'kids', 'ethnic', 'anarkali', 'festive'] }
  ),
  P(
    'boys-striped-polo-tshirt',
    "Boys' Striped Polo T-Shirt",
    'kids-fashion',
    'Kartly Kids',
    499,
    699,
    55,
    'A colourful striped polo in breathable cotton piqué.',
    ['Cotton piqué', 'Polo collar', 'Short sleeves', 'Ages 4–14 years'],
    { tags: ['boys', 'kids', 't-shirt', 'tshirt', 'polo'] }
  ),
  P(
    'boys-denim-waistcoat-set',
    "Boys' Denim Waistcoat, Shirt & Jeans Set",
    'kids-fashion',
    'Kartly Kids',
    1099,
    1499,
    22,
    'A dapper three-piece set with a denim waistcoat, printed shirt and jeans.',
    ['Denim waistcoat', 'Printed cotton shirt', 'Stretch jeans', 'Ages 2–10 years'],
    { tags: ['boys', 'kids', 'set', 'party'] }
  ),
  P(
    'boys-hooded-jacket-and-jeans',
    "Boys' Hooded Jacket & Jeans Set",
    'kids-fashion',
    'Kartly Kids',
    1499,
    1999,
    14,
    'A cosy hooded jacket with a tee and slim jeans for cooler days.',
    ['Hooded jacket', 'Cotton T-shirt', 'Slim jeans', 'Ages 4–12 years'],
    { tags: ['boys', 'kids', 'jacket', 'winterwear'] }
  ),
];

module.exports = { CATEGORIES, BRANDS, PRODUCTS };
